<?php

$digitalWorkerOperatorCapabilities = [
    'ai.chat_attachments.manage',
    'ai.digital_worker.view',
    'ai.digital_worker.execute',
    'ai.tool_delegation_status.execute',
    'ai.tool_document_analysis.execute',
    'ai.tool_guide.execute',
    'ai.tool_image_analysis.execute',
    'ai.tool_memory_get.execute',
    'ai.tool_memory_search.execute',
    'ai.tool_navigate.execute',
    'ai.tool_notification.execute',
    'ai.tool_query_data.execute',
    'ai.tool_system_info.execute',
    'ai.tool_web_fetch.execute',
    'ai.tool_web_search.execute',
    'ai.tool_worker_list.execute',
    'ai.tool_workspace.view',
];

$dwPowerUserAdditionalCapabilities = [
    'ai.chat_model.manage',
    'ai.tool_artisan.execute',
    'ai.tool_bash.execute',
    'ai.tool_browser.execute',
    'ai.tool_browser_evaluate.execute',
    'ai.tool_delegate.execute',
    'ai.tool_message.execute',
    'ai.tool_schedule.execute',
    'ai.tool_workspace.manage',
    'ai.tool_write_js.execute',
];

return [
    'domains' => [
        'core' => 'Core platform modules',
        'workflow' => 'Workflow and state transitions',
        'ai' => 'AI and Digital Worker capabilities',
        'messaging' => 'Multi-channel messaging capabilities',
        'admin' => 'Administrative operations',
    ],

    'verbs' => [
        'view',
        'list',
        'create',
        'update',
        'delete',
        'submit',
        'approve',
        'reject',
        'execute',
        'impersonate',
        'manage',
        'grant',
        'revoke',
        'send',
        'react',
        'edit',
        'media',
        'poll',
        'search',
    ],

    // Capabilities owned by the base framework (no module to host them yet).
    // Module-owned capabilities live in each module's Config/authz.php
    // and are auto-discovered by App\Base\Authz\ServiceProvider.
    'capabilities' => [
        'ai.chat_attachments.manage',
        'ai.chat_model.manage',
        'ai.digital_worker.view',
        'ai.digital_worker.execute',
        'ai.tool_artisan.execute',
        'ai.tool_bash.execute',
        'ai.tool_browser.execute',
        'ai.tool_browser_evaluate.execute',
        'ai.tool_delegate.execute',
        'ai.tool_delegation_status.execute',
        'ai.tool_guide.execute',
        'ai.tool_memory_get.execute',
        'ai.tool_memory_search.execute',
        'ai.tool_navigate.execute',
        'ai.tool_notification.execute',
        'ai.tool_query_data.execute',
        'ai.tool_schedule.execute',
        'ai.tool_system_info.execute',
        'ai.tool_web_fetch.execute',
        'ai.tool_message.execute',
        'ai.tool_document_analysis.execute',
        'ai.tool_image_analysis.execute',
        'ai.tool_web_search.execute',
        'ai.tool_worker_list.execute',
        'ai.tool_write_js.execute',
        'ai.tool_workspace.view',
        'ai.tool_workspace.manage',
        'messaging.account.manage',
        'messaging.account.grant',
        'messaging.account.revoke',
        'messaging.whatsapp.send',
        'messaging.whatsapp.react',
        'messaging.whatsapp.media',
        'messaging.telegram.send',
        'messaging.telegram.react',
        'messaging.telegram.edit',
        'messaging.telegram.delete',
        'messaging.telegram.poll',
        'messaging.linkedin.send',
        'messaging.signal.send',
        'messaging.imessage.send',
        'messaging.slack.send',
        'messaging.email.send',
        'messaging.sms.send',
        'messaging.any.search',
        'admin.user.impersonate',
        'admin.role.list',
        'admin.role.view',
        'admin.role.create',
        'admin.role.update',
        'admin.role.delete',
        'admin.principal_role.list',
        'admin.capability.list',
        'admin.principal_capability.list',
        'admin.decision_log.list',
    ],

    'decision_log_retention_days' => 90,

    // System roles that aggregate capabilities across modules.
    // Module-scoped roles may also be declared in module Config/authz.php.
    'roles' => [
        'core_admin' => [
            'name' => 'Core Administrator',
            'description' => 'System role with all capabilities. New capabilities are automatically granted.',
            'grant_all' => true,
        ],
        'user_viewer' => [
            'name' => 'User Viewer',
            'description' => 'Read-only access to user management.',
            'capabilities' => [
                'core.user.list',
                'core.user.view',
            ],
        ],
        'user_editor' => [
            'name' => 'User Editor',
            'description' => 'Read-write access to user management.',
            'capabilities' => [
                'core.user.list',
                'core.user.view',
                'core.user.create',
                'core.user.update',
                'core.user.delete',
            ],
        ],
        'employee_viewer' => [
            'name' => 'Employee Viewer',
            'description' => 'Read-only access to employee, company, and address data.',
            'capabilities' => [
                'core.employee.view',
                'core.employee.list',
                'core.employee_type.list',
                'core.company.view',
                'core.company.list',
                'core.address.view',
                'core.address.list',
                'core.geonames.view',
                'core.geonames.list',
            ],
        ],
        'employee_editor' => [
            'name' => 'Employee Editor',
            'description' => 'Read-write access to employees, employee types, companies, and addresses.',
            'capabilities' => [
                'core.employee.view',
                'core.employee.list',
                'core.employee.create',
                'core.employee.update',
                'core.employee.delete',
                'core.employee_type.list',
                'core.employee_type.create',
                'core.employee_type.update',
                'core.employee_type.delete',
                'core.company.view',
                'core.company.list',
                'core.company.create',
                'core.company.update',
                'core.company.delete',
                'core.address.view',
                'core.address.list',
                'core.address.create',
                'core.address.update',
                'core.address.delete',
                'core.geonames.view',
                'core.geonames.list',
            ],
        ],
        'auditor' => [
            'name' => 'Auditor',
            'description' => 'Read-only access to decision logs, system logs, and sessions for compliance.',
            'capabilities' => [
                'admin.decision_log.list',
                'admin.system_log.list',
                'admin.system_session.list',
            ],
        ],
        'digital_worker_operator' => [
            'name' => 'Digital Worker Operator',
            'description' => 'View and execute Digital Workers with basic tool access.',
            'capabilities' => $digitalWorkerOperatorCapabilities,
        ],
        'dw_power_user' => [
            'name' => 'DW Power User',
            'description' => 'Full Digital Worker tool access including artisan, bash, delegation, scheduling, media analysis, and JS execution.',
            'capabilities' => [
                ...$digitalWorkerOperatorCapabilities,
                ...$dwPowerUserAdditionalCapabilities,
            ],
        ],
        'messaging_reader' => [
            'name' => 'Messaging Reader',
            'description' => 'Read-only access to messaging — search conversations across channels.',
            'capabilities' => [
                'messaging.any.search',
            ],
        ],
        'messaging_responder' => [
            'name' => 'Messaging Responder',
            'description' => 'DW that responds to inbound messages — send and react on configured channels.',
            'capabilities' => [
                'messaging.whatsapp.send',
                'messaging.whatsapp.react',
                'messaging.telegram.send',
                'messaging.telegram.react',
                'messaging.slack.send',
                'messaging.email.send',
                'messaging.any.search',
            ],
        ],
        'messaging_operator' => [
            'name' => 'Messaging Operator',
            'description' => 'Full messaging power on granted channels — send, react, edit, delete, polls, and media.',
            'capabilities' => [
                'messaging.whatsapp.send',
                'messaging.whatsapp.react',
                'messaging.whatsapp.media',
                'messaging.telegram.send',
                'messaging.telegram.react',
                'messaging.telegram.edit',
                'messaging.telegram.delete',
                'messaging.telegram.poll',
                'messaging.linkedin.send',
                'messaging.signal.send',
                'messaging.imessage.send',
                'messaging.slack.send',
                'messaging.email.send',
                'messaging.sms.send',
                'messaging.any.search',
            ],
        ],
        'messaging_admin' => [
            'name' => 'Messaging Admin',
            'description' => 'Supervisor role for managing channel accounts and DW access grants.',
            'capabilities' => [
                'messaging.account.manage',
                'messaging.account.grant',
                'messaging.account.revoke',
            ],
        ],
        'system_viewer' => [
            'name' => 'System Viewer',
            'description' => 'Read-only access to system infrastructure: migrations, seeders, jobs, cache, scheduled tasks, and sessions.',
            'capabilities' => [
                'admin.system_migration.list',
                'admin.system_seeder.list',
                'admin.system_log.list',
                'admin.system_job.list',
                'admin.system_failed_job.list',
                'admin.system_job_batch.list',
                'admin.system_scheduled_task.list',
                'admin.system_info.view',
                'admin.system_session.list',
                'admin.system_cache.view',
            ],
        ],
    ],
];
