<?php

// SPDX-License-Identifier: AGPL-3.0-only
// (c) Ng Kiat Siong <kiatsiong.ng@gmail.com>

namespace App\Modules\Core\AI\Tools;

use App\Modules\Core\AI\Contracts\DigitalWorkerTool;

/**
 * Delegation status polling tool for Digital Workers.
 *
 * Checks the status of a previously dispatched task by its dispatch_id.
 * Returns current status, timing, and result preview when available.
 *
 * Note: Task dispatch is currently queued-only (not yet persisted to database).
 * This tool returns a "queued" status for any syntactically valid dispatch_id.
 * Full persistence and real status tracking will be implemented when
 * LaraTaskDispatcher is upgraded to use Laravel queues and database storage.
 *
 * Gated by `ai.tool_delegation_status.execute` authz capability.
 */
class DelegationStatusTool implements DigitalWorkerTool
{
    /**
     * Expected prefix for dispatch IDs generated by LaraTaskDispatcher.
     */
    private const DISPATCH_ID_PREFIX = 'dw_dispatch_';

    public function name(): string
    {
        return 'delegation_status';
    }

    public function description(): string
    {
        return 'Check the status of a previously dispatched task. '
            .'Provide the dispatch_id returned by delegate_task to see '
            .'whether the task is queued, running, completed, or failed.';
    }

    public function parametersSchema(): array
    {
        return [
            'type' => 'object',
            'properties' => [
                'dispatch_id' => [
                    'type' => 'string',
                    'description' => 'The dispatch_id returned by delegate_task. '
                        .'Format: "dw_dispatch_<random>".',
                ],
            ],
            'required' => ['dispatch_id'],
        ];
    }

    public function requiredCapability(): ?string
    {
        return 'ai.tool_delegation_status.execute';
    }

    public function execute(array $arguments): string
    {
        $dispatchId = $arguments['dispatch_id'] ?? '';

        if (! is_string($dispatchId) || trim($dispatchId) === '') {
            return 'Error: No dispatch_id provided.';
        }

        $dispatchId = trim($dispatchId);

        if (! $this->isValidDispatchId($dispatchId)) {
            return 'Error: Invalid dispatch_id format. '
                .'Expected format: "dw_dispatch_<random>" as returned by delegate_task.';
        }

        return $this->lookupStatus($dispatchId);
    }

    /**
     * Validate that the dispatch ID has the expected format.
     */
    private function isValidDispatchId(string $dispatchId): bool
    {
        return str_starts_with($dispatchId, self::DISPATCH_ID_PREFIX)
            && strlen($dispatchId) > strlen(self::DISPATCH_ID_PREFIX);
    }

    /**
     * Look up the dispatch status.
     *
     * Currently returns a placeholder response since task dispatches are
     * not yet persisted to database. When LaraTaskDispatcher is upgraded
     * to queue real jobs, this method will query the dispatch store.
     */
    private function lookupStatus(string $dispatchId): string
    {
        return json_encode([
            'dispatch_id' => $dispatchId,
            'status' => 'queued',
            'message' => 'Task dispatch is queued. Real-time status tracking will be available '
                .'when the delegation execution pipeline is fully implemented.',
            'checked_at' => now()->toIso8601String(),
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }
}
