<?php

// SPDX-License-Identifier: AGPL-3.0-only
// (c) Ng Kiat Siong <kiatsiong.ng@gmail.com>

namespace App\Modules\Core\AI\Tools;

use App\Base\AI\Enums\ToolCategory;
use App\Base\AI\Enums\ToolRiskClass;
use App\Base\AI\Tools\AbstractTool;
use App\Base\AI\Tools\Schema\ToolSchemaBuilder;
use App\Base\AI\Tools\ToolArgumentException;

/**
 * Delegation status polling tool for Digital Workers.
 *
 * Checks the status of a previously dispatched task by its dispatch_id.
 * Returns current status, timing, and result preview when available.
 *
 * Note: Task dispatch is currently queued-only (not yet persisted to database).
 * This tool returns a "queued" status for any syntactically valid dispatch_id.
 * Full persistence and real status tracking will be implemented when
 * LaraTaskDispatcher is upgraded to use Laravel queues and database storage.
 *
 * Gated by `ai.tool_delegation_status.execute` authz capability.
 */
class DelegationStatusTool extends AbstractTool
{
    /**
     * Expected prefix for dispatch IDs generated by LaraTaskDispatcher.
     */
    private const DISPATCH_ID_PREFIX = 'dw_dispatch_';

    public function name(): string
    {
        return 'delegation_status';
    }

    public function description(): string
    {
        return 'Check the status of a previously dispatched task. '
            .'Provide the dispatch_id returned by delegate_task to see '
            .'whether the task is queued, running, completed, or failed.';
    }

    protected function schema(): ToolSchemaBuilder
    {
        return ToolSchemaBuilder::make()
            ->string(
                'dispatch_id',
                'The dispatch_id returned by delegate_task. '
                    .'Format: "dw_dispatch_<random>".'
            )->required();
    }

    public function category(): ToolCategory
    {
        return ToolCategory::DELEGATION;
    }

    public function riskClass(): ToolRiskClass
    {
        return ToolRiskClass::READ_ONLY;
    }

    public function requiredCapability(): ?string
    {
        return 'ai.tool_delegation_status.execute';
    }

    protected function handle(array $arguments): string
    {
        $dispatchId = $this->requireString($arguments, 'dispatch_id');

        if (! $this->isValidDispatchId($dispatchId)) {
            throw new ToolArgumentException(
                'Invalid dispatch_id format. '
                    .'Expected format: "dw_dispatch_<random>" as returned by delegate_task.'
            );
        }

        return $this->lookupStatus($dispatchId);
    }

    /**
     * Validate that the dispatch ID has the expected format.
     */
    private function isValidDispatchId(string $dispatchId): bool
    {
        return str_starts_with($dispatchId, self::DISPATCH_ID_PREFIX)
            && strlen($dispatchId) > strlen(self::DISPATCH_ID_PREFIX);
    }

    /**
     * Look up the dispatch status.
     *
     * Currently returns a placeholder response since task dispatches are
     * not yet persisted to database. When LaraTaskDispatcher is upgraded
     * to queue real jobs, this method will query the dispatch store.
     */
    private function lookupStatus(string $dispatchId): string
    {
        return json_encode([
            'dispatch_id' => $dispatchId,
            'status' => 'queued',
            'message' => 'Task dispatch is queued. Real-time status tracking will be available '
                .'when the delegation execution pipeline is fully implemented.',
            'checked_at' => now()->toIso8601String(),
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }
}
