<?php

// SPDX-License-Identifier: AGPL-3.0-only
// (c) Ng Kiat Siong <kiatsiong.ng@gmail.com>

namespace App\Modules\Core\AI\Tools;

use App\Base\AI\Enums\ToolCategory;
use App\Base\AI\Enums\ToolRiskClass;
use App\Base\AI\Tools\AbstractTool;
use App\Base\AI\Tools\Concerns\ProvidesToolMetadata;
use App\Base\AI\Tools\Schema\ToolSchemaBuilder;
use App\Base\AI\Tools\ToolArgumentException;
use App\Base\AI\Tools\ToolResult;
use App\Modules\Core\AI\Models\AgentTaskDispatch;

/**
 * Delegation status polling tool for Agents.
 *
 * Queries the ai_agent_task_dispatches table to check the status of a
 * previously dispatched task. Returns current status, timing, assigned
 * agent, and result summary when available.
 *
 * Gated by `ai.tool_delegation_status.execute` authz capability.
 */
class DelegationStatusTool extends AbstractTool
{
    use ProvidesToolMetadata;

    /**
     * Expected prefix for dispatch IDs generated by LaraTaskDispatcher.
     */
    private const DISPATCH_ID_PREFIX = 'agent_dispatch_';

    public function name(): string
    {
        return 'delegation_status';
    }

    public function description(): string
    {
        return 'Check the status of a previously dispatched task. '
            .'Provide the dispatch_id returned by delegate_task to see '
            .'whether the task is queued, running, completed, or failed.';
    }

    protected function schema(): ToolSchemaBuilder
    {
        return ToolSchemaBuilder::make()
            ->string(
                'dispatch_id',
                'The dispatch_id returned by delegate_task. '
                    .'Format: "agent_dispatch_<random>".'
            )->required();
    }

    public function category(): ToolCategory
    {
        return ToolCategory::DELEGATION;
    }

    public function riskClass(): ToolRiskClass
    {
        return ToolRiskClass::READ_ONLY;
    }

    public function requiredCapability(): ?string
    {
        return 'ai.tool_delegation_status.execute';
    }

    protected function toolMetadata(): array
    {
        return [
            'displayName' => 'Delegation Status',
            'summary' => 'Check the status of a previously dispatched task.',
            'explanation' => 'Queries the status of a task dispatched via Delegate Task by its dispatch ID. '
                .'Returns status (queued/running/succeeded/failed), timing, and result summary.',
            'limits' => [
                'Read-only status check',
            ],
        ];
    }

    protected function handle(array $arguments): ToolResult
    {
        $dispatchId = $this->requireString($arguments, 'dispatch_id');

        if (! $this->isValidDispatchId($dispatchId)) {
            throw new ToolArgumentException(
                'Invalid dispatch_id format. '
                    .'Expected format: "agent_dispatch_<random>" as returned by delegate_task.'
            );
        }

        return ToolResult::success($this->lookupStatus($dispatchId));
    }

    /**
     * Validate that the dispatch ID has the expected format.
     */
    private function isValidDispatchId(string $dispatchId): bool
    {
        return str_starts_with($dispatchId, self::DISPATCH_ID_PREFIX)
            && strlen($dispatchId) > strlen(self::DISPATCH_ID_PREFIX);
    }

    /**
     * Look up the dispatch status from the database.
     */
    private function lookupStatus(string $dispatchId): string
    {
        $dispatch = AgentTaskDispatch::query()->find($dispatchId);

        if ($dispatch === null) {
            return json_encode([
                'dispatch_id' => $dispatchId,
                'status' => 'not_found',
                'message' => 'No dispatch record found for this ID.',
                'checked_at' => now()->toIso8601String(),
            ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        }

        $data = [
            'dispatch_id' => $dispatch->id,
            'status' => $dispatch->status,
            'employee_id' => $dispatch->employee_id,
            'employee_name' => data_get($dispatch->meta, 'employee_name'),
            'task' => $dispatch->task,
            'ticket_id' => $dispatch->ticket_id,
            'created_at' => $dispatch->created_at?->toIso8601String(),
            'started_at' => $dispatch->started_at?->toIso8601String(),
            'finished_at' => $dispatch->finished_at?->toIso8601String(),
            'checked_at' => now()->toIso8601String(),
        ];

        if ($dispatch->status === 'succeeded') {
            $data['result_summary'] = $dispatch->result_summary;
        }

        if ($dispatch->status === 'failed') {
            $data['error_message'] = $dispatch->error_message;
        }

        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }
}
